[font]
normal = { family = "Fira Code", style = "Regular"}
bold = { family = "Fira Code", style = "Bold"}
italic = { family = "Fira Code", style = "Italic"}
bold_italic = { family = "Fira Code", style = "Bold Italic"}

[colors.primary]
background = '0x0F1419'
foreground =  '0xC0C5CE'

[colors.normal]
black = '0x2B303B'
red = '0xBF616A'
green = '0xA3BE8C'
yellow = '0xEBCB8B'
blue = '0x8FA1B3'
magenta = '0xB48EAD'
cyan = '0x96B5B4'
white = '0xC0C5CE'

[colors.bright]
black = '0x65737E'
red = '0xBF616A'
green = '0xA3BE8C'
yellow = '0xEBCB8B'
blue = '0x8FA1B3'
magenta = '0xB48EAD'
cyan = '0x96B5B4'
white = '0xEFF1F5'

[colors.cursor]
text = '0x0F1419'
cursor = '0xC0C5CE'
